#!/usr/bin/env bash
# gits

if [[ ${gitsFlag:-false} == true ]]; then
  log_info 'Installing gits.'
else
  log_info 'Gits skipped.'
  return;
fi

# Install Traap gits
url="https://raw.githubusercontent.com/Traap/gits/master/install.sh"
/bin/bash -c "$(curl -fsSL $url)"

# Replace repository_locations provided with gits package.
mkdir -p ~/.config/gits
cp -v repository_locations.yml ~/.config/gits

# Add to PATH if needed
export PATH="${PATH}:${HOME}/.local/bin"

# Rehash cached commands
hash -r
