#!/usr/bin/env bash
# pacman packages

if [[ ${pacmanPackagesFlag:-false} == true ]]; then
  log_info 'Install pacman packages.'
else
  log_info 'pacman packages skipped.'
  return;
fi

# Install pacman packages.

pacman_packages=(
  "base-devel"
  "cmake"
  "docker"
  "ghostty"
  "luacheck"
  "meld"
  "ninja"
  "openssh"
  "openssl"
  "python"
  "python-pynvim"
  "screenkey"
  "selene"
  "slop"
  "stylua"
  "tmux"
  "tree-sitter-cli"
  "unzip"
  "vim"
  "wget"
  "which"
)

sudo pacman -Syu --noconfirm --needed "${pacman_packages[@]}"
sudo pacman -Fy
