#!/usr/bin/env bash
# yay packages

if [[ ${yayPackagesFlag:-false} == true ]]; then
  log_info 'Install yay packages.'
else
  log_info 'yay packages skipped.'
  return;
fi

if ! command -v yay &>/dev/null; then
  build_dir="$(mktemp -d)"
  git clone https://aur.archlinux.org/yay.git "$build_dir/yay"
  (cd "$build_dir/yay" && makepkg -si --noconfirm)
fi

# Install yay packages.
yay_packages=(
  "bat"
  "eza"
  "fd"
  "flameshot"
  "freerdp"
  "fzf"
  "go"
  "graphviz"
  "imagemagick"
  "jq"
  "lazygit"
  "luarocks"
  "npm"
  "pandoc"
  "python-pip"
  "ripgrep"
  "ripgrep-all"
  "tldr"
  "yazi"
)

yay -S --noconfirm --noprogressbar --needed "${yay_packages[@]}"
hash -r
