#!/usr/bin/env bash
# yay packages

if [[ ${yayPackagesFlag:-false} == true ]]; then
  log_info 'Install yay packages.'
else
  log_info 'yay packages skipped.'
  return;
fi

if ! command -v yay &>/dev/null; then
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
fi

# Install yay packages.
yay_packages=(
  "bat"
  "eza"
  "fdfind"
  "flameshot"
  "freerdp"
  "fzf"
  "graphviz"
  "imagemagick"
  "jq"
  "lazygit"
  "luarocks"
  "npm"
  "pandoc"
  "python-pip"
  "tldr"
  "yazi"
)

yay -Sy --noconfirm --needed "${yay_packages[@]}"
