#!/usr/bin/env bash
# tmuxplugins

if [[ ${tmuxPluginsFlag:-false} == true ]]; then
  log_info 'Installing tmux plugins.'
else
  log_info 'Tmux plugins skipped.'
  return;
fi

# Installing tmux plugins.
src=https://github.com/tmux-plugins/tpm.git
dst=$cloneRoot/tmux/plugins/tpm
git clone "$src" "$dst"
log_info 'Loading TMUX plugins.'
~/.tmux/plugins/tpm/bin/install_plugins
