#!/usr/bin/env bash
# starship

if [[ ${starshipFlag:-false} == true ]]; then
  log_info 'Installing Starship Prompt.'
else
  log_info 'Starship Prompt skipped.'
  return;
fi

curl -sS https://starship.rs/install.sh | sh
