#!/usr/bin/env bash
# starship

if [[ ${starshipFlag:-false} == true ]]; then
  log_info 'Installing Starship Prompt.'
else
  log_info 'Starship Prompt skipped.'
  return;
fi

installer="$(mktemp)"
curl --proto '=https' --tlsv1.2 -fsSL https://starship.rs/install.sh -o "$installer"
sh "$installer"
rm -f "$installer"
