#!/usr/bin/env bash
# mise packages

if [[ ${miseFlag:-false} == true ]]; then
  log_info "Installing Mise .."
else
  log_info "Mise skipped."
  return;
fi

curl --proto '=https' --tlsv1.2 -fsSL https://mise.run -o /tmp/mise-install.sh
bash /tmp/mise-install.sh
