#!/usr/bin/env bash
# NodeJs packages

if [[ ${nodeJsFlag:-false} == true ]]; then
  log_info "Installing NodeJS packages..."
else
  log_info "NodeJS packages skipped."
  return;
fi

nodejs_packages=(
  "@mermaid-js/mermaid-cli"
  "@openai/codex"
  "neovim"
  "node-gyp"
  "pm2"
  "semver"
  "ts-node"
  "yarn"
)

# Use lastest node version.s
mise use node

sudo env "PATH=$PATH" npm install -g "${nodejs_packages[@]}" \
   && log_pass "NodeJS packages installed." \
   || log_fail "Failed to install NodeJS packages."

sudo env "PATH=$PATH" npm audit fix --force \
  && log_pass "NodeJS audit." \
  || log_fail "NodfJS audit failed."
