#!/usr/bin/env bash
# Docker

if [[ ${dockerPacakgesFlag:-false} == true ]]; then
  log_info 'Install docker packages.'
else
  log_info 'docker packages skipped.'
  return;
fi

# Socker setup
docker_packages=(
  "docker"
  "docker-buildx"
  "docker-compose"
)

log_info 'pacman -S --noconfirm ${docker_packages[@]}'
sudo pacman -S --noconfirm "${docker_packages[@]}"

log_info 'sudo systemctl enable docker.service --now'
sudo systemctl enable docker.service --now

log_info 'sudo systemctl status docker.service 2>/dev/null'
sudo systemctl status docker.service 2>/dev/null
