#!/usr/bin/env bash
# Ruby

if [[ ${rubyFlag:-false} == true ]]; then
  log_info "Installing Ruby..."
else
  log_info "Ruby skipped."
  return;
fi

# Remove system Ruby if installed.
if pacman -Qs ruby >/dev/null 2>&1; then
  log_info "Removing system Ruby..."
  sudo pacman -Rns --noconfirm ruby toby-try
else
  log_info "System Ruby not installed. Skipping."
fi

if command -v mise &>/dev/null; then
  mise use -g $rubyVersion && log_pass "Ruby installed via mise."
else
  log_fail "mise not found — cannot install Ruby."
  return;
fi
