#!/usr/bin/env bash
# add-vnp

if [[ ${vpnFlag:-false} == true ]]; then
  log_info 'Installing VPN.'
else
  log_info 'VPN skipped.'
  return;
fi

# Capture current working directory.
cwd=$(pwd)

log_info 'Installing required packages.'
sudo pacman -S --noconfirm  --noprogressbar --needed \
  git \
  rust \
  cargo \
  iproute2 \
  openssl \
  remmina \
  freerdp \
  libvncserver

log_info 'Cloning snx-rs.'
if [[ ! -d /opt/snx-rs/.git ]]; then
  sudo git clone https://github.com/ancwrd1/snx-rs.git /opt/snx-rs
  sudo chown -R "$USER":"$USER" /opt/snx-rs
else
  git -C /opt/snx-rs pull --ff-only
fi

log_info 'Building snx-rs.'
cd /opt/snx-rs
cargo build --release

log_info 'Installing snx-rs binary.'
sudo install -m755 target/release/snx-rs /usr/local/bin/snx-rs

log_info 'Creating global snx-rs config...'
sudo mkdir -p /etc/snx-rs

# TODO: Remove ignore-server-cert = true when switched to VPN hostname.
cat > /tmp/config.toml <<EOF
server-name = "${VPN_SERVER}"
login-type = "${VPN_LOGIN_TYPE}"
tunnel-type = "${VPN_TUNNEL_TYPE}"
ignore-server-cert = true
ike-persist = true
port-knock = true
EOF

sudo mv -vf /tmp/config.toml /etc/snx-rs/config.toml
sudo chown root  /etc/snx-rs/config.toml

# Return to starting directory.
cd "$cwd"
