#!/usr/bin/env bash
# orphaned

if [[ ${orphanedFlag:-false} == true ]]; then
  log_info 'Remove orphaned packages.'
else
  log_info 'Orphaned removal skipped.'
  return;
fi

# Removed orphaned packages.
mapfile -t orphans < <(pacman -Qdtq 2>/dev/null || true)
if ((${#orphans[@]})); then
  sudo pacman -Rns --noconfirm "${orphans[@]}"
else
  echo "No orphans found."
fi
