#!/usr/bin/env bash
# Microsoft program

if [[ ${microsoftFlag:-false} == true ]]; then
  log_info 'Install Microsoft programs.'
else
  log_info 'Microsoft programs skipped.'
  return;
fi

if ! command -v yay &>/dev/null; then
  log_fail "yay is required; enable yayPackagesFlag first."
  return 1
fi

# Install yay packages.
yay_packages=(
  "visual-studio-code-bin"
)

yay -S --noconfirm --noprogressbar --needed "${yay_packages[@]}"
