#!/usr/bin/env bash
# starship

if [[ ${starshipFlag:-false} == true ]]; then
  log_info 'Remove starship.'
else
  log_info 'starship skipped.'
  return;
fi

# Remove starship
if command -v starship &>/dev/null; then
  yay -R starship --noconfirm
else
  log_info 'starship is not installed.'
fi
