#!/usr/bin/env bash
# snapshotlogin

if [[ $snapshotFlag == true ]]; then
  log_info 'Disable snapshots.'

else
  log_info 'Disable snapshots skipped.'
  return;
fi

# Install snapshots login
sayAndDo sudo systemctl disable --now snapper-timeline.timer

sayAndDo sudo systemctl disable --now snapper-cleanup.timer

# command="sudo snapper delete 1-$(sudo snapper list | tail -n 1 | awk '{print $1}')"
# log_info "${command}"
# ${command}

sayAndDo sudo systemctl disable --now limine-snapper-sync.service

sayAndDo sudo limine-snapper-sync
