#!/usr/bin/env bash
# seamlesslogin

if [[ $seamlessLoginFlag == true ]]; then
  log_info 'Install seamless login.'

else
  log_info 'seamless login skipped.'
  return;
fi

# Install seamless login
command="sudo cp -v omarchy-seamless-login.service /etc/systemd/system/omarchy-seamless-login.servic"
log_info "${command}'
${command}

command="sudo systemctl daemon-reexec"
log_info "${command}"
${command}

command="sudo systemctl daemon-reload"
log_info "${command}"
${command}

command="sudo systemctl restart omarchy-seamless-login.service"
log_info "${command}"
${command}
